version: '3.9'

services:
  mindsdb-db:
    image: mindsdb/mindsdb:latest
    ports:
      - "47334:47334"
      - "47335:47335"

  backend:
    build:
      context: backend/
    ports:
      - "8000:8000"
    environment:
      MARIADB_DATABASE_URL: "mysql://<you-mysql-username>:<your-mysql-password>@<public-ip>/btc_price"  # replace with your mysql credentials
      MINDSDB_URL: "http://mindsdb-db:47334/api/sql/query"

  frontend:
    build:
      context: frontend/
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: "http://backend:8000/predict"